
// Vistoria - core app.js (static hosting friendly)
// Uses localStorage for demo purposes. For production, connect to Firebase/Supabase.
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8);}
function loadPins(){ let grid=document.getElementById('grid'); if(!grid) return; let pins=JSON.parse(localStorage.getItem('pins')||'[]'); pins = pins.slice().reverse();
  grid.innerHTML = pins.map(p=>`<div class='pin'>${p.type==='video'?`<video controls src='${p.img}'></video>`:`<img src='${p.img}' loading='lazy'>`}<div class='meta'><div class='left'><img src='${p.avatar||'./branding/favicon.png'}' class='avatar'><div><div class='title'>${p.title}</div><div class='small'>${p.user}</div></div></div><div><span class='small' onclick="likePin('${p.id}')">❤ ${p.likes||0}</span></div></div></div>`).join('');
}
function likePin(id){ let pins=JSON.parse(localStorage.getItem('pins')||'[]'); let i=pins.findIndex(x=>x.id===id); if(i===-1) return; pins[i].likes=(pins[i].likes||0)+1; localStorage.setItem('pins',JSON.stringify(pins)); loadPins(); }
function searchPins(){ let term=(document.getElementById('searchInput')?.value||'').toLowerCase(); let pins=JSON.parse(localStorage.getItem('pins')||'[]'); let grid=document.getElementById('grid'); grid.innerHTML = pins.filter(p=>p.title.toLowerCase().includes(term)|| (p.description||'').toLowerCase().includes(term)).slice().reverse().map(p=>`<div class='pin'>${p.type==='video'?`<video controls src='${p.img}'></video>`:`<img src='${p.img}' loading='lazy'>`}<div class='meta'><div class='left'><img src='${p.avatar||'./branding/favicon.png'}' class='avatar'><div><div class='title'>${p.title}</div><div class='small'>${p.user}</div></div></div><div><span class='small' onclick="likePin('${p.id}')">❤ ${p.likes||0}</span></div></div></div>`).join(''); }
function uploadPin(){ let title=document.getElementById('title')?.value; let desc=document.getElementById('description')?.value; let file=document.getElementById('imgFile')?.files[0]; let user=localStorage.getItem('vistUser')||'Invitado'; if(!file||!title){alert('Completa todo');return;} let reader=new FileReader(); reader.onload=function(e){ let pins=JSON.parse(localStorage.getItem('pins')||'[]'); let type=file.type.startsWith('video')?'video':'image'; pins.push({id:uid(),title:title,description:desc,img:e.target.result,user:user,avatar:localStorage.getItem('vistAvatar')||'',likes:0,type:type,createdAt:Date.now()}); localStorage.setItem('pins',JSON.stringify(pins)); alert('Subido'); window.location='index.html'; }; reader.readAsDataURL(file); }
function openUpload(){ window.location='upload.html'; }
function login(){ let user=document.getElementById('user')?.value||prompt('Usuario'); if(!user) return alert('Usuario requerido'); localStorage.setItem('vistUser',user); window.location='profile.html'; }
function saveProfile(){ const name=document.getElementById('profileName')?.value; const file=document.getElementById('avatarFile')?.files[0]; if(name) localStorage.setItem('vistUser',name); if(file){ const r=new FileReader(); r.onload=function(e){ localStorage.setItem('vistAvatar',e.target.result); alert('Perfil guardado'); window.location='profile.html'; }; r.readAsDataURL(file);} else{ alert('Perfil guardado'); window.location='profile.html'; } }
function loadProfile(){ const name=localStorage.getItem('vistUser')||'Invitado'; const avatar=localStorage.getItem('vistAvatar')||'./branding/favicon.png'; const el=document.getElementById('usernameDisplay'); if(el) el.innerText='Usuario: '+name; const img=document.getElementById('profileAvatar'); if(img) img.src=avatar; const pins=JSON.parse(localStorage.getItem('pins')||'[]').filter(p=>p.user===name); const count=document.getElementById('userPinsCount'); if(count) count.innerText=pins.length; }
(function initDemo(){ if(localStorage.getItem('pins')) return; let demo=[{id:uid(),title:'Playa atardecer',img:'https://picsum.photos/600/400?1',user:'Admin',avatar:'',likes:3,type:'image'},{id:uid(),title:'Receta sana',img:'https://picsum.photos/400/600?2',user:'Chef',avatar:'',likes:1,type:'image'},{id:uid(),title:'Video demo',img:'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',user:'Video',avatar:'',likes:0,type:'video'}]; localStorage.setItem('pins',JSON.stringify(demo)); })();
